spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minorproject1_jbdl77?createDatabaseIfNotExist=true
    username: root
    password: root1234
  jpa:
    hibernate.ddl-auto: create
    show-sql: true

server:
  port: 9090

custom_property:
  secret_key: secret@123
